
"""initial

Revision ID: 12ee07e206ce
Revises: 
Create Date: 2026-04-25 03:48:38.432444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ee07e206ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('users_email_idx'), 'users', ['email'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('conversations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conversations_pkey'))
    )
    op.create_index(op.f('conversations_user_id_idx'), 'conversations', ['user_id'], unique=False)
    op.create_table('conversation_shares',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('shared_by', sa.String(length=36), nullable=False),
    sa.Column('shared_with', sa.String(length=36), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('permission', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('conversation_shares_conversation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by'], ['users.id'], name=op.f('conversation_shares_shared_by_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with'], ['users.id'], name=op.f('conversation_shares_shared_with_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conversation_shares_pkey')),
    sa.UniqueConstraint('conversation_id', 'shared_with', name='uq_share_conv_user'),
    sa.UniqueConstraint('share_token', name=op.f('conversation_shares_share_token_key'))
    )
    op.create_index(op.f('conversation_shares_conversation_id_idx'), 'conversation_shares', ['conversation_id'], unique=False)
    op.create_index(op.f('conversation_shares_shared_with_idx'), 'conversation_shares', ['shared_with'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('messages_conversation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('messages_conversation_id_idx'), 'messages', ['conversation_id'], unique=False)
    op.create_table('chat_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('parsed_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('chat_files_message_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('chat_files_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_files_pkey'))
    )
    op.create_index(op.f('chat_files_user_id_idx'), 'chat_files', ['user_id'], unique=False)
    op.create_table('message_ratings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('rating IN (1, -1)', name=op.f('message_ratings_ck_rating_value_check')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('message_ratings_message_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('message_ratings_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('message_ratings_pkey')),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_message_user_rating')
    )
    op.create_index(op.f('message_ratings_message_id_idx'), 'message_ratings', ['message_id'], unique=False)
    op.create_index(op.f('message_ratings_user_id_idx'), 'message_ratings', ['user_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('tool_call_id', sa.String(length=100), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('args', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('tool_calls_message_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tool_calls_pkey'))
    )
    op.create_index(op.f('tool_calls_message_id_idx'), 'tool_calls', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('tool_calls_message_id_idx'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('message_ratings_user_id_idx'), table_name='message_ratings')
    op.drop_index(op.f('message_ratings_message_id_idx'), table_name='message_ratings')
    op.drop_table('message_ratings')
    op.drop_index(op.f('chat_files_user_id_idx'), table_name='chat_files')
    op.drop_table('chat_files')
    op.drop_index(op.f('messages_conversation_id_idx'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('conversation_shares_shared_with_idx'), table_name='conversation_shares')
    op.drop_index(op.f('conversation_shares_conversation_id_idx'), table_name='conversation_shares')
    op.drop_table('conversation_shares')
    op.drop_index(op.f('conversations_user_id_idx'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('users_email_idx'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
