export { useAuthStore } from "./auth-store";
export {
  hasAnyPermission,
  hasBranchScope,
  hasMasterRead,
  hasPermission,
  hasRole,
  hasStoreScope,
  isBranchManagerRole,
  isFrontlineCashierNav,
  isFrontlineWarehouseNav,
  isStoreManagerRole,
  isSystemLevelUser,
  isSystemManage,
} from "./access";
export type { AccessGate } from "./gates";
export {
  allowAll,
  gateBranchCreate,
  gateBranchHubNavigationPage,
  gateBranchPagesWithinStore,
  gateBranchUpdate,
  gateBranchView,
  gateCustomerCreate,
  gateCustomerUpdate,
  gateCustomerView,
  gateDashboard,
  gateGoodsReceiptConfirm,
  gateGoodsReceiptCreate,
  gateGoodsReceiptView,
  gateInventoryTransactionView,
  gateInventoryView,
  gateMasterCatalog,
  gateMasterCatalogManagementPages,
  gateOrderCancel,
  gateOrderConfirm,
  gateOrderCreate,
  gateOrderView,
  gateProductCatalogMutate,
  gateProductCreate,
  gateProductView,
  gateRbacArea,
  gateRbacAreaRoute,
  gateRbacOverridesManage,
  gateRbacPermissionsView,
  gateRbacRolesView,
  gateReportView,
  gateReturnCreate,
  gateReturnView,
  gateSettingsArea,
  gateStocktakeCreate,
  gateStocktakeView,
  gateStoreCreate,
  gateStoreDataRead,
  gateStoreScopedUserAssignBranch,
  gateStoreScopedUserView,
  gateStoreStaffArea,
  gateStoreUpdate,
  gateStoreView,
  gateSupplierMutate,
  gateSystemManage,
  gateTransferCreate,
  gateTransferReceive,
  gateTransferSend,
  gateTransferView,
  gateWarehouseHubNavigationPage,
  gateWarehousePagesWithinStore,
} from "./gates";
