spring.application.name=sales_management_mini
spring.profiles.active=dev

# Cấu hình Upload File chung
spring.servlet.multipart.max-file-size=${MAX_UPLOAD_FILE_SIZE:3MB}
spring.servlet.multipart.max-request-size=${MAX_UPLOAD_REQUEST_SIZE:12MB}

# App Custom Config chung
app.auth.register-default-role=${REGISTER_DEFAULT_ROLE:STORE_MANAGER}
app.upload.product-images-dir=${PRODUCT_IMAGES_DIR:uploads/products}

# JPA chung
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
spring.jpa.properties.hibernate.format_sql=true

# JWT chung (Có thể override ở prod)
app.jwt.secret=${JWT_SECRET:dev-only-change-in-production-minimum-32-characters-long}
app.jwt.expiration-ms=86400000

# Flyway mặc định tắt
spring.flyway.enabled=false